# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: health trackers
#setting up the job to run on a push request on the main branch
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    #installing dependencies    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: execute py script
            run: |
              python run.py
            env:
              key: ${{ secrets.key }} #if run.py requires passwords..etc, set it as secrets
     - name: Commit files
       id: commit
       run: |
         git config --local user.email "action@github.com"
         git config --local user.name "github-actions"
         git add --all
         if [ -z "$(git status --porcelain)" ]; then
            echo "::set-output name=push::false"
         else
            git commit -m "Add changes" -a
            echo "::set-output name=push::true"
         fi
       shell: bash
     - name: Push changes
       if: steps.commit.outputs.push == 'true'
       uses: ad-m/github-push-action@master
       with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
